# Generated by Django 4.0.3 on 2022-04-18 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id_chap', models.TextField(primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('titre', models.TextField()),
                ('descriptif', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Chapitres',
            },
        ),
        migrations.CreateModel(
            name='Norme',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('titre', models.TextField()),
                ('version', models.IntegerField()),
                ('descriptif', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Normes',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('point', models.TextField()),
                ('type_actif', models.TextField()),
                ('fct_sec', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Points',
            },
        ),
        migrations.CreateModel(
            name='Question_Generale',
            fields=[
                ('id_qst', models.TextField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('id_norme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.norme', verbose_name='Normes')),
            ],
            options={
                'verbose_name_plural': 'Questions_Generales',
            },
        ),
        migrations.CreateModel(
            name='SC_niv1',
            fields=[
                ('version', models.IntegerField()),
                ('id_Sc1', models.TextField(primary_key=True, serialize=False)),
                ('titre', models.TextField()),
                ('objectif', models.TextField()),
                ('id_chap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.chapitre', verbose_name='Chapitres')),
                ('id_norme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.norme', verbose_name='Normes')),
            ],
            options={
                'verbose_name_plural': 'Sc_niv1',
            },
        ),
        migrations.CreateModel(
            name='SC_niv2',
            fields=[
                ('version', models.IntegerField()),
                ('id_Sc2', models.TextField(primary_key=True, serialize=False)),
                ('titre', models.TextField()),
                ('objectif', models.TextField()),
                ('id_Sc1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.sc_niv1', verbose_name='Sc_niv1')),
                ('id_chap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.chapitre', verbose_name='Chapitres')),
                ('id_norme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.norme', verbose_name='Normes')),
            ],
            options={
                'verbose_name_plural': 'Sc_niv2',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id_test', models.AutoField(primary_key=True, serialize=False)),
                ('id_client', models.IntegerField()),
                ('finished', models.BooleanField()),
                ('date', models.DateField()),
                ('last_point', models.TextField()),
                ('id_norme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.norme', verbose_name='Normes')),
            ],
            options={
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.CreateModel(
            name='SC_niv3',
            fields=[
                ('version', models.IntegerField()),
                ('id_Sc3', models.TextField(primary_key=True, serialize=False)),
                ('titre', models.TextField()),
                ('objectif', models.TextField()),
                ('id_Sc1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.sc_niv1', verbose_name='Sc_niv1')),
                ('id_Sc2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.sc_niv2', verbose_name='Sc_niv2')),
                ('id_chap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.chapitre', verbose_name='Chapitres')),
                ('id_norme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.norme', verbose_name='Normes')),
            ],
            options={
                'verbose_name_plural': 'Sc_niv3',
            },
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id_reponse', models.TextField(primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('reponse', models.BooleanField()),
                ('id_Sc1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.sc_niv1', verbose_name='Sc_niv1')),
                ('id_Sc2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.sc_niv2', verbose_name='Sc_niv2')),
                ('id_Sc3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.sc_niv3', verbose_name='Sc_niv3')),
                ('id_chap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.chapitre', verbose_name='Chapitres')),
                ('id_norme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.norme', verbose_name='Normes')),
                ('id_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.point', verbose_name='Points')),
                ('id_qst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.question_generale', verbose_name='Questions_Generales')),
                ('id_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.test', verbose_name='Tests')),
            ],
        ),
        migrations.AddField(
            model_name='point',
            name='id_Sc1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.sc_niv1', verbose_name='Sc_niv1'),
        ),
        migrations.AddField(
            model_name='point',
            name='id_Sc2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.sc_niv2', verbose_name='Sc_niv2'),
        ),
        migrations.AddField(
            model_name='point',
            name='id_Sc3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.sc_niv3', verbose_name='Sc_niv3'),
        ),
        migrations.AddField(
            model_name='point',
            name='id_chap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.chapitre', verbose_name='Chapitres'),
        ),
        migrations.AddField(
            model_name='point',
            name='id_norme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.norme', verbose_name='Normes'),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='id_norme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.norme', verbose_name='Normes'),
        ),
    ]
