# Generated by Django 4.0.3 on 2022-04-21 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='id',
        ),
        migrations.AddField(
            model_name='point',
            name='id_point',
            field=models.TextField(default='default-id', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='point',
            name='titre',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='descriptif',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='norme',
            name='descriptif',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='norme',
            name='version',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='fct_sec',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='id_Sc1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.sc_niv1', verbose_name='Sc_niv1'),
        ),
        migrations.AlterField(
            model_name='point',
            name='id_Sc2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.sc_niv2', verbose_name='Sc_niv2'),
        ),
        migrations.AlterField(
            model_name='point',
            name='id_Sc3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.sc_niv3', verbose_name='Sc_niv3'),
        ),
        migrations.AlterField(
            model_name='point',
            name='type_actif',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='id_Sc1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.sc_niv1', verbose_name='Sc_niv1'),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='id_Sc2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.sc_niv2', verbose_name='Sc_niv2'),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='id_Sc3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.sc_niv3', verbose_name='Sc_niv3'),
        ),
        migrations.AlterField(
            model_name='sc_niv1',
            name='objectif',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sc_niv2',
            name='objectif',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sc_niv3',
            name='objectif',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='id_test',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='last_point',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
