# Generated by Django 4.0.3 on 2022-05-18 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_reponse_comment_alter_filemodel_doc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapitre',
            options={'verbose_name': 'Chapitres'},
        ),
        migrations.AlterModelOptions(
            name='norme',
            options={'verbose_name': 'Normes'},
        ),
        migrations.AlterModelOptions(
            name='point',
            options={'verbose_name': 'Points'},
        ),
        migrations.AlterModelOptions(
            name='question_generale',
            options={'verbose_name': 'Questions_Generales'},
        ),
        migrations.AlterModelOptions(
            name='sc_niv1',
            options={'verbose_name': 'Sc_niv1'},
        ),
        migrations.AlterModelOptions(
            name='sc_niv2',
            options={'verbose_name': 'Sc_niv2'},
        ),
        migrations.AlterModelOptions(
            name='sc_niv3',
            options={'verbose_name': 'Sc_niv3'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Tests'},
        ),
    ]
