# Generated by Django 4.0.3 on 2022-05-18 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_reponse_options_alter_point_id_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponse',
            name='id_chap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.chapitre'),
        ),
    ]
