# Generated by Django 4.0.3 on 2022-05-18 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_reponse_id_chap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponse',
            name='id_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.point'),
        ),
    ]
