# Generated by Django 4.0.3 on 2022-05-18 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_reponse_id_point'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapitre',
            options={'verbose_name_plural': 'Chapitres'},
        ),
        migrations.AlterModelOptions(
            name='norme',
            options={'verbose_name_plural': 'Normes'},
        ),
        migrations.AlterModelOptions(
            name='point',
            options={'verbose_name_plural': 'Points'},
        ),
        migrations.AlterModelOptions(
            name='question_generale',
            options={'verbose_name_plural': 'Questions_Generales'},
        ),
        migrations.AlterModelOptions(
            name='reponse',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sc_niv1',
            options={'verbose_name_plural': 'Sc_niv1'},
        ),
        migrations.AlterModelOptions(
            name='sc_niv2',
            options={'verbose_name_plural': 'Sc_niv2'},
        ),
        migrations.AlterModelOptions(
            name='sc_niv3',
            options={'verbose_name_plural': 'Sc_niv3'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name_plural': 'Tests'},
        ),
        migrations.AlterField(
            model_name='point',
            name='id_point',
            field=models.TextField(default='default-id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='id_chap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.chapitre', verbose_name='Chapitres'),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='id_norme',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.norme', verbose_name='Normes'),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='id_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.point', verbose_name='Points'),
        ),
    ]
