# Generated by Django 4.0.3 on 2022-05-18 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_alter_chapitre_options_alter_norme_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponse',
            name='id_norme',
        ),
    ]
