# Generated by Django 4.0.3 on 2022-05-18 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_remove_reponse_id_norme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponse',
            name='id_point',
        ),
    ]
