# Generated by Django 4.0.3 on 2022-05-25 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_alter_test_id_client_alter_test_id_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='id_norme',
        ),
        migrations.AddField(
            model_name='reponse',
            name='id_norme',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='User.norme', verbose_name='Normes'),
            preserve_default=False,
        ),
    ]
