# Generated by Django 4.0.3 on 2022-05-27 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0015_test_id_norme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id_qst', models.TextField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('id_norme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.norme', verbose_name='Normes')),
                ('id_point', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.point', verbose_name='Points')),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('raison', models.TextField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.AlterField(
            model_name='reponse',
            name='id_qst',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.question', verbose_name='Questions'),
        ),
        migrations.DeleteModel(
            name='Question_Generale',
        ),
    ]
