# Generated by Django 4.0.3 on 2022-05-27 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0016_question_client_alter_reponse_id_qst_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loi',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('titre', models.TextField()),
                ('descriptif', models.TextField(blank=True, default=None, null=True)),
                ('file_name', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'Lois',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='date_fin',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='num_fisc',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('is_super', models.BooleanField(default=False)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
            options={
                'verbose_name_plural': 'Admins',
            },
        ),
    ]
