# Generated by Django 4.0.3 on 2022-05-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0022_alter_loi_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loi',
            name='file_name',
            field=models.FileField(blank=True, default=None, null=True, upload_to='static'),
        ),
    ]
