# Generated by Django 4.0.3 on 2022-06-05 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0023_alter_loi_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='doc',
            field=models.FileField(upload_to='C:\\pfe\\Projet\\User\\static\\media'),
        ),
        migrations.AlterField(
            model_name='loi',
            name='file_name',
            field=models.FileField(blank=True, default=None, null=True, upload_to='C:\\pfe\\Projet\\User\\static\\media/pdf'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('date', models.DateField()),
                ('loi', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.loi', verbose_name='Lois')),
                ('norme', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.norme', verbose_name='Normes')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
        ),
    ]
